"""Independent parser, likelihood, sample-separation and provenance checks."""
from collections import Counter
import hashlib
import importlib.util
import json
from pathlib import Path
import tempfile
import unittest
from unittest.mock import patch

import numpy as np
from orthopolity.linguistic_resources import (
    Sentence, document_bootstrap, fit_positive_family, fitted_models,
    log_probabilities, parse_conllu, pronunciations, training_vocabulary, words,
)

ROOT = Path(__file__).resolve().parents[1]
SPEC = importlib.util.spec_from_file_location("linguistic_runner_test", ROOT / "experiments/run_linguistic_resources.py")
RUNNER = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(RUNNER)

class LinguisticResourceTests(unittest.TestCase):
    def test_original_text_preserves_contractions_and_documents(self):
        corpus = """# newdoc id = email-example
# sent_id = email-example-0001
# text = I can't go.
1\tI\t_\t_\t_\t_\t0\t_\t_\t_
2\tca\t_\t_\t_\t_\t0\t_\t_\t_
3\tn't\t_\t_\t_\t_\t0\t_\t_\t_

# sent_id = email-example-0002
# text = We won't.
1\tWe\t_\t_\t_\t_\t0\t_\t_\t_
"""
        sentences = parse_conllu(corpus)
        self.assertEqual([s.document for s in sentences], ["email-example", "email-example"])
        self.assertEqual(words(sentences[0].text)[0], ["i", "can't", "go"])
        self.assertEqual(sentences[0].genre, "email")
        with self.assertRaises(ValueError):
            parse_conllu(corpus.replace("# newdoc id = email-example\n", ""))

    def test_unicode_run_not_accidentally_split_into_ascii_fragments(self):
        accepted, rejected = words("École café can't don’t TEST e-mail a12b")
        self.assertEqual(accepted, ["can't", "don't", "test", "e", "mail", "a", "b"])
        self.assertEqual(rejected, ["école", "café"])
        self.assertEqual(words("cafe\u0301")[1], ["café"])

    def test_canonical_pronunciation_ignores_alternates_and_stress_digits(self):
        dictionary = pronunciations("a AH0\na(2) EY1\ncan't K AE1 N T\nread R EH1 D # comment\nread(2) R IY1 D\n")
        self.assertEqual(dictionary, {"a": 1, "can't": 4, "read": 3})
        with self.assertRaises(ValueError):
            pronunciations("word W ER1 D\nword W ER1 D")

    def test_vocabulary_and_counts_use_only_fitting_genres(self):
        sentences = [Sentence("email-a-1", "email-a", "email", "cat cat dog"),
                     Sentence("reviews-b-1", "reviews-b", "reviews", "dog dog fox fox fox")]
        vocab, counts, features, all_count = training_vocabulary(sentences, {"cat": 3, "dog": 3, "fox": 4}, ["email"], 2)
        self.assertEqual(vocab, ["cat"])
        np.testing.assert_array_equal(counts, [2])
        self.assertNotIn("fox", all_count)
        np.testing.assert_array_equal(features, [[3, 3]])

    def test_recovers_identifiable_synthetic_composite(self):
        raw = np.array([[1,1], [2,1], [1,3], [3,2], [4,5]], dtype=float)
        x = np.log(raw)
        theta = np.array([1.2, .7])
        # Exact expected proportions, not generated by a fitted sample.
        weights = raw[:,0]**-theta[0] * raw[:,1]**-theta[1]
        result = fit_positive_family(x, weights / weights.sum() * 10000)
        np.testing.assert_allclose(result["theta"], theta, atol=2e-6)
        self.assertLess(result["projected_gradient_max"], 1e-7)

    def test_positive_boundary_and_same_feature_equality(self):
        result = fit_positive_family(np.array([[1.], [2.], [3.]]), [1, 2, 10])
        self.assertEqual(result["theta"], [0.])
        self.assertEqual(result["boundary"], [True])
        lp = log_probabilities([[1, 2], [1, 2], [3, 4]], [2, 1])
        self.assertEqual(lp[0], lp[1])
        self.assertAlmostEqual(np.exp(lp).sum(), 1.)

    def test_model_normalization_and_fixed_baselines(self):
        feature = np.array([[1, 1], [2, 3], [4, 3]])
        models = fitted_models(feature, [40, 30, 10])
        for row in models.values():
            self.assertAlmostEqual(np.exp(row["log_probability"]).sum(), 1.)
        np.testing.assert_allclose(np.exp(models["inverse_letters"]["log_probability"]), np.array([1,.5,.25])/1.75)
        np.testing.assert_allclose(np.exp(models["training_unigram"]["log_probability"]), np.array([40.5,30.5,10.5])/81.5)

    def test_heldout_word_exclusions_are_exhaustive(self):
        s = Sentence("reviews-a-1", "reviews-a", "reviews", "cat dog fox quux café")
        vector, excluded, candidates, ascii_count = RUNNER.sentence_counts(
            s, {"cat": 0}, {"cat": 3, "dog": 3, "fox": 4}, {"cat": 9, "dog": 2})
        self.assertEqual(vector.tolist(), [1])
        self.assertEqual((candidates, ascii_count), (5, 4))
        self.assertEqual(Counter(reason for reason, word in excluded),
                         Counter(["training_count_below_five", "unseen_in_fitting_genres", "dictionary_absent", "non_ascii_letter_run"]))
        self.assertEqual(int(vector.sum()) + sum(excluded.values()), candidates)

    def test_document_bootstrap_is_paired_and_ratio_of_sums(self):
        # Both models differ by exactly .3 nats/token in every document.
        counts = np.array([1., 10., 100.])
        first = np.array([2., 40., 300.])
        loss = np.column_stack([first, first + .3*counts])
        a = document_bootstrap(loss, counts, replicates=100, seed=6)
        b = document_bootstrap(loss, counts, replicates=100, seed=6)
        np.testing.assert_array_equal(a, b)
        np.testing.assert_allclose(a[:,1]-a[:,0], .3, atol=1e-14)
        self.assertTrue(any(abs(a[:,0] - first.mean()/counts.mean()) > .1))

    def test_source_mutation_rejected(self):
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            directory = root / "data"
            directory.mkdir()
            records = []
            for name, url, stage, role in RUNNER.FETCH.SOURCES:
                if stage != "train":
                    continue
                path = directory / name
                path.write_bytes(b"retained source")
                record = dict(filename=path.name, url=url, stage=stage, sha256=hashlib.sha256(path.read_bytes()).hexdigest(), size_bytes=path.stat().st_size)
                records.append(record)
                (directory / (name + ".receipt.json")).write_text(json.dumps(record))
            (directory / "sources.json").write_text(json.dumps(dict(sources=records)))
            with patch.object(RUNNER, "ROOT", root):
                self.assertEqual(len(RUNNER.verify_sources(directory, "train")), 6)
                (directory / "ewt-README.md").write_bytes(b"changed source!")
                with self.assertRaises(ValueError):
                    RUNNER.verify_sources(directory, "train")

if __name__ == "__main__":
    unittest.main()
